### ISSUE TITLE
Search a recently lost ball in the direction in which it was recently seen

### ISSUE THREAD

**Issue by ftsell** [bit-bots/bitbots_behavior#10]
When a ball is lost, the robot should look in the direction in which the ball was last seen

**Comment by NFiedler** [comment]
This method bears the danger of getting stuck on false positives. Sometimes a reset is the best option.

**Comment by ftsell** [comment]
That's why we should only do it for a short time and then return to our normal pattern search.
Basically a quick glance

**Comment by NFiedler** [comment]
Isn't this done inherently by the ball tracking behavior? We are looking at the ball until ball_seen returns NO. and this is done when the ball was last seen in a longer time than ball_lost_time. Meaning when we lose the ball, we are still looking towards our last belief until ball_lost_time runs out.

**Comment by ftsell** [comment]
Yes which means that if the ball moves, we look at the last known spot and hope that it is still in view once that spot is reached so we can continue.
What I'm suggesting is that if this does not work we just continue into the same direction.

Like, yeah sure it's an edge case and most normal cases are covered by the existing behavior but I think this could help us for faster moving balls
