### ISSUE TITLE
Use an external animation config file

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/bitbots_behavior#11]
The names if animations (e.g. for a kick) should be collected and configured in a separate config file. As @timonegk mentioned in #9 , the file could be merged with the one in the bit-bots HCM which would add dependencies.

**Comment by SammyRamone** [comment]
@NFiedler this file does already exist? is this issue done?

**Comment by NFiedler** [comment]
I wiol check that in the afternoon today.
