### ISSUE TITLE
Goalie should walk parallel to backline when the ball is near (before it becomes dangerous)

### ISSUE THREAD

**Issue by ftsell** [bit-bots/bitbots_behavior#15]
Currently a goalie stands in the goal and looks at the ball when it approaches said goal.
If the ball is not determined dangerous, the goalie does nothing.
In my opinion he should not move out of the goal but try to block the ball, therefore moving parallel to the backline

**Comment by NFiedler** [comment]
See #5. We need a localization for that stuff.

**Comment by NFiedler** [comment]
implemented in #104 .
