### ISSUE TITLE
Change role dynamically

### ISSUE THREAD

**Issue by SammyRamone** [bit-bots/bitbots_behavior#174]
Change role in game dynamically. For example if the offense player gets a red card, one of the offense players should become offensive

- [ ] check gamecontroller for red card
- [ ] check team comm to check if other robot is still there

**Comment by jaagut** [comment]
> Change role in game dynamically. For example if the offense player gets a red card, one of the ~offense~ defense players should become offensive

I assume, it should be defense?

Also, if we only have one defense (by default, one plays offense instead, or on colleague is penalized), the remaining defender should be positioned to the role position 0

**Comment by SammyRamone** [comment]
done in https://github.com/bit-bots/bitbots_behavior/pull/196
