### ISSUE TITLE
Decide whether to use `__` or `_` for private fields 

### ISSUE THREAD

**Issue by jgueldenstein** [bit-bots/bitbots_behavior#204]
https://github.com/bit-bots/bitbots_behavior/pull/201#discussion_r654261027

**Comment by jaagut** [comment]
Here as a clarification:

- `_single`: Is a convention for private attributes
- `__double`: Seems to actual syntax (mangling)
- `__double_with_trailing__`: Is for _magix methods_

Source: https://www.geeksforgeeks.org/private-variables-python/

**Comment by NFiedler** [comment]
I vote for `_`

**Comment by Flova** [comment]
As Jan said `_` is the correct one if you don't want to use a fix used for inheritance in private scopes for that.
