### ISSUE TITLE
Reintroduce multiple defender positions 

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_behavior#276]
See #274 

```python
generalized_role_position = role_positions[f'{self.blackboard.blackboard.duty}_{pos_number}']
# Was changed to 
generalized_role_position = role_positions[f'{self.blackboard.blackboard.duty}_{0}']
```

**Comment by val-ba** [comment]
What number does the goalie have? If the goalie is no. 1 everytime, this should be fine.

**Comment by Flova** [comment]
The goalie has no number and is handled separately.
https://github.com/bit-bots/bitbots_behavior/blob/a3a7c89b9c28640e92565fb22c9c6f38f42ecc83/bitbots_body_behavior/bitbots_body_behavior/actions/go_to_role_position.py#L15
The config that is loaded looks like this: https://github.com/bit-bots/bitbots_behavior/blob/a3a7c89b9c28640e92565fb22c9c6f38f42ecc83/bitbots_body_behavior/config/body_behavior.yaml#L35

Also, this:
https://github.com/bit-bots/bitbots_behavior/blob/a3a7c89b9c28640e92565fb22c9c6f38f42ecc83/bitbots_body_behavior/bitbots_body_behavior/actions/go_to_role_position.py#L24 
looks like it should be

```python
generalized_role_position = role_positions['offense'][f'{kickoff_type}_{pos_number}']
```

if we look at the configs structure.

And as described in the main part of this issue this
https://github.com/bit-bots/bitbots_behavior/blob/a3a7c89b9c28640e92565fb22c9c6f38f42ecc83/bitbots_body_behavior/bitbots_body_behavior/actions/go_to_role_position.py#L27

leads to only a centered defense position being available.

Imo we could also remove the position randomization for the offense players, as it is not really needed. And can lead to a weird walk in where the robots cross each other quite tightly. See https://github.com/bit-bots/bitbots_behavior/blob/a3a7c89b9c28640e92565fb22c9c6f38f42ecc83/bitbots_body_behavior/bitbots_body_behavior/actions/go_to_role_position.py#L19

If we stop randomizing the offense supporter position, we could also position the defender off center on the other side, which would be nice against strong kicks.

**Comment by val-ba** [comment]
https://github.com/bit-bots/bitbots_behavior/blob/master/bitbots_body_behavior/bitbots_body_behavior/actions/go_to_role_position.py#L19
Why do we do the if? Why can't we just load the pos_number directly?

**Comment by val-ba** [comment]
How do we know whether someone is offense supporter or not?

**Comment by Flova** [comment]
> How do we know whether someone is offense supporter or not?

The supporters are the offense players that don't handle the ball. While positioning at the role position, they would go to `offense_active_1` or `offense _active_2`. It the side aka 1 or 2 is chosen randomly, but I would be fine with removing it. There is also the passive position if the others have kickoff, but it is the same principal.

**Comment by Flova** [comment]
> https://github.com/bit-bots/bitbots_behavior/blob/master/bitbots_body_behavior/bitbots_body_behavior/actions/go_to_role_position.py#L19 Why do we do the if? Why can't we just load the pos_number directly?

We always want to have a center offense player that positions itself for the kickoff. The ones to the left and right are chosen randomly. But I would prefer it without the randomization.

**Comment by val-ba** [comment]
> We always want to have a center offense player that positions itself for the kickoff. The ones to the left and right are chosen randomly. But I would prefer it without the randomization.

That means we could load it directly?

**Comment by Flova** [comment]
I guess
