### ISSUE TITLE
get_bioik_ik takes no positional argument

### ISSUE THREAD

**Issue by val-ba** [bit-bots/bitbots_behavior#278]
https://github.com/bit-bots/bitbots_behavior/blob/master/bitbots_head_behavior/bitbots_head_behavior/actions/look_at.py#L41

When testing the behavior in the simulator, we see that get_bioik_ik() does not take any arguments. Is it okay to delete self.request?

**Comment by Flova** [comment]
I think the bio_ik Python interface that we currently use is still ros1 and needs to be ported/rebuild. It is mainly relevant for the ball tracking and we don't do it that much, but is should be fixed never the less.

**Comment by Flova** [comment]
Solved by https://github.com/bit-bots/bitbots_motion/pull/385
