### ISSUE TITLE
Publisher in world_model_capsule to be used in head behavior?

### ISSUE THREAD

**Issue by val-ba** [bit-bots/bitbots_behavior#306]
Right now the head and body behavior have their own world_model_capsule which does the same thing when tracking what ball is seen.
While rewriting the head behavior in cpp, a lot of world_model_capsule functionalities are used like the ball_last_seen time which on the other hand uses many other methods in the world_model_capsule.
There are some publisher which are marked as debug purpose: https://github.com/bit-bots/bitbots_behavior/blob/master/bitbots_blackboard/bitbots_blackboard/capsules/world_model_capsule.py#L81

@Flova  @jaagut @timonegk 
Wouldnt it be possible to just subscribe to e.g. used_ball to know when the last ball was seen instead of rewriting the whole world_model_capsule? Or maybe adding additional publisher and subscriber.

**Comment by jaagut** [comment]
Currently, I don't have the capacity to go deep into your question, but a few weeky ago, I have refactored and cleaned up the world_model_capsule (still untested). This might clear up some confusion: https://github.com/bit-bots/bitbots_behavior/blob/refactor/world_model_capsule/bitbots_blackboard/bitbots_blackboard/capsules/world_model_capsule.py

**Comment by Flova** [comment]
The main issue with the approach would be that we can not run the head behavior without the body behavior. The ideal case would be to rip the ball selection stuff out of the world model capsule and move it e.g. to the ball filter so it already merges it with the team ball and publishes the different balls so the body and head behavior can subscribe to them.
