### ISSUE TITLE
head_mover sometimes dies randomly

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_behavior#324]
The head mover sometimes dies randomly with a segmentation fault. There is no helpful error message, so we will have to investigate some more.
I think it said "Looking at point" very often, then "Received goal request" once, then "Looking at point" a few times, then it died.

When the head mover is dead, the behavior is not doing anything because it is waiting for the head mover service.

**Comment by jaagut** [comment]
Will close this now, as we did not reproduce this behavior since and the code has been refactored, which might have resolved this issue.
