### ISSUE TITLE
Use visual compass data

### ISSUE THREAD

**Issue by ftsell** [bit-bots/bitbots_behavior#35]

**Comment by SammyRamone** [comment]
how is this meant? dont we just want to integrate the data into the world model? it doesnt seem right to directly use the data in the behaviour

**Comment by NFiedler** [comment]
Actually, it would be most useful in the localization in my opinion. But the behavior could use it directly when no localization is available. Which is currently the case.

**Comment by NFiedler** [comment]
@Flova, @SammyRamone, @MonsterUntermBett, and others: what do you think about this? should we still integrate this into the behavior or just use it for localization? 
Using it twice seems kinda wrong... I think. Depending on the accuracy of the compass. 
If we want to use this in the behavior, I'd suggest to use it as our goal direction when there is none and to flip it by 180 degrees (yes, it would just be an approximation) if we see a goal and the compass suggests it is ours. However then this would just be part of the NoLocalizationBehavior I think.

**Comment by SammyRamone** [comment]
I think it should be included into the localization for the standard case and used directly for no localization behaviour

**Comment by Flova** [comment]
I think this is an old issue from a time, where the localization was not really ready yet, so plan was to use the no localization behavior, but check if the goal is ours or not via the visual compass. This is indeed not needed anymore if we use the localization.

**Comment by NFiedler** [comment]
What? No, it most definitely is needed! as long as we can't be certain that the localization works in every situation, we will need this. The behavior can switch to the NoLocalizationBehavior in every situation the localization is not certain enough.

**Comment by Flova** [comment]
But I think in this case we should use the most simple no localization backup behavior possible. I think the usage of the visual compass only makes sense in combination with the localization and we should focus our development resources on this and a simple backup, while not maintaining all steps in between.

**Comment by NFiedler** [comment]
why shouldn't we include the compass? It can help to reduce the number of own goals. Especially in a situation in which we used localization a situation in which the robot faces the own goa lis more common.

**Comment by Flova** [comment]
Because the visual compass is also a source of complexity and possible errors, therefore I wouldn't include it in the backup behavior and focus our resources a a better localization, visual compass combination. A proper integration of the visual compass in the localization would handle this whole problem. If e.g. the localization uses "most" of its orientational information from the visual compass (if it currently sees any features above the field), the output state is likely to have the same orientation. Even if the localization "fails" because it got the wrong local maximum for the other inputs, its likely that this state also has the orientation from the visual compass.

**Comment by NFiedler** [comment]
I think we have different definitions of backup behavior. The NoLocalizationBehavior is not necessarily meant to work as a backup behavior (however, it is currently used as such). It's just what we do when there is no reliable localization available (meaning in this second, not in this game or competition). However, I do think that when we use not a single value of localization precision as currently proposed in #72 but two values (one for location and one for orientation), we might use these valued to decide whether we use the orientation alone or the full pose.

**Comment by NFiedler** [comment]
Okay, so this is closed as the behavior will use visual compass data via the localization even when the position certainty is very bad. #72 will be adapted to the new requirements.
