### ISSUE TITLE
World model visualization: show objects as long as they are in the robot's world model

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_behavior#62]
## Expected behavior
The objects in the robot's local world model should be visualized as long as the robot thinks that they are at the visualized place.

## Current behavior
Currently, the objects stay only for five seconds. But e.g. a goal remains in the robot's world model for a much longer time.

## Possible Solution
Set the lifetime to the duration specified in `goal_lost_time` or `ball_lost_time` respectively.
Update the marker when the object is seen again.

**Comment by NFiedler** [comment]
As #63 is merged now, can this be closed? @timonegk
