### ISSUE TITLE
body behavior: goal_lost_time is ignored

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_behavior#66]
## Expected behavior
The robot should search for the goal again after the time specified in the `goal_lost_time` parameter.

## Current behavior
Since commit 33329055fb274f65b7da99a9cdc1c3792e8a1581, the `goal_lost_time` parameter is ignored.

## Possible Solution
Revert 33329055fb274f65b7da99a9cdc1c3792e8a1581 and instead increase the parameter to avoid future confusions.

**Comment by NFiedler** [comment]
we need to reconsider everything in this regard with the new localization as a goal position can also be inferred from the robots position.
