### ISSUE TITLE
Pause walking when the localization has to readjust

### ISSUE THREAD

**Issue by ftsell** [bit-bots/bitbots_behavior#74]

**Comment by NFiedler** [comment]
should the localization decide it or should the behavior decide based on the covariance matrix?

**Comment by timonegk** [comment]
We discussed that it should be decided by the behaviour. I updated the issue description accordingly.

**Comment by NFiedler** [comment]
So this is waiting for #72 . Then we can use a precision threshold to use the localization. when the threshold is not surpassed we could try for a limited amount of time to relocalize using the different head behavior.

**Comment by NFiedler** [comment]
Additionally, a timer could be used to get out of wrong local optima.
