### ISSUE TITLE
Body Behavior: 'WorldModelCapsule' object has no attribute 'goal_width'

### ISSUE THREAD

**Issue by TanjaSmiley** [bit-bots/bitbots_behavior#78]
## Expected behavior

The class variable goal_width should be initialized in the WorldModelCapsule.
## Current behavior

The class variable goal_width in the WorldModelCapsule is used in the methods get_map_based_opp_goal_left_post_uv() and get_map_based_opp_goal_right_post_uv(). However, this variable is not initialized.
## Steps to Reproduce

1. 
2.
3.
...

## Context (Environment)

- [ ] RViz
- [ ] Simulator
- [ ] Robot
- [ ] Local

**Comment by NFiedler** [comment]
Closed by #79
